### model
model_name_or_path: /workspace/LLaMA-Factory/models

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: haha13
template: llama3
cutoff_len: 4096
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: saves_lora/Full+1.7IP+1
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
